# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00a2d74b8134911430606fe82347cd6a659bbaf8b4b62e110746df73a4d4c1121b17137a1c00d5058ac1fd410874f1bb7ddbf29984e43c80cb464c36f7a51a24

test:
  secret_key_base: 58e725e95a1aa92ea55131373779f24eb43e5e83063e28c5474d4fb0e5244768c8c3c1c7ceb1021fba8b85b0e29c18b33a8c9ccd3f1e31202a85be85cc2f6908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
